name: WakaTime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "10 3 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: wakatime-gist
        uses: abordage/wakatime-box@master
        env:
          # SUPPORTED: last_7_days, last_30_days, last_6_months, last_year
          INPUT_DATE_RANGE: last_7_days
          # NUMBER OF LANGUAGES DISPLAYED
          INPUT_MAX_RESULT: 5
          #
          INPUT_PRINT_SUMMARY: true

          INPUT_GH_TOKEN: ${{ secrets.GH_TOKEN }}
          INPUT_WAKA_API_KEY: ${{ secrets.WAKA_API_KEY }}
          INPUT_GIST_ID: ${{ secrets.GIST_ID }}